name: Docker Build & Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: marinho14
          password: Mlops1234*

      - name: Build and push streamlit image
        uses: docker/build-push-action@v3
        with:
          context: ./streamlit
          file: ./streamlit/Dockerfile
          push: true
          tags: marinho14/streamlit:latest

      - name: Build and push mlflow image
        uses: docker/build-push-action@v3
        with:
          context: ./mlflow
          file: ./mlflow/Dockerfile
          push: true
          tags: marinho14/mlflow:latest

      - name: Build and push inference image
        uses: docker/build-push-action@v3
        with:
          context: ./inference
          file: ./inference/Dockerfile
          push: true
          tags: marinho14/inference:latest

      - name: Build and push jupyter image
        uses: docker/build-push-action@v3
        with:
          context: ./myjupyter
          file: ./myjupyter/Dockerfile
          push: true
          tags: marinho14/jupyter:latest
